# Generated by Django 4.2.1 on 2023-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_product_quantity_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
