# Generated by Django 4.2.1 on 2023-08-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_razor_pay_order_id_order_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='is_paid',
        ),
    ]
