# Generated by Django 4.2.1 on 2023-08-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_rename_descrption_aboutus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='brand_logo',
            field=models.ImageField(default=False, upload_to='brand_logo'),
        ),
    ]
