# Generated by Django 4.2.1 on 2023-08-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_product_shipping_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_fee',
        ),
    ]
