# Generated by Django 4.2.1 on 2023-08-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_remove_product_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=8),
        ),
    ]
