# Generated by Django 4.2.1 on 2023-08-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_product_initial_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='initial_stock',
        ),
    ]
