# Generated by Django 4.2.1 on 2023-08-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_remove_product_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
