# Generated by Django 4.2.1 on 2023-08-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_product_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippping_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
