# Generated by Django 4.2.1 on 2023-08-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_order_shippping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.shippingaddress'),
        ),
    ]
